apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoproxy
  template:
    metadata:
      labels:
        app: demoproxy
    spec:
      containers:
      - name: demoproxy
        image: worming/demoproxy:v1.0
        ports:
        - containerPort: 8080
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1